name: CreateRepo

on:
  workflow_dispatch:
    inputs:
      reponame:
        description: 'Repo name'
        required: true
        type: string

jobs:
  handle_devops_event:
    runs-on: ubuntu-latest
    name: "Create repo : ${{ github.event.inputs.reponame }}" 
    steps:
      - name: Toon ontvangen input
        run: |
          echo "Creatin repo: ${{ github.event.inputs.reponame }}"
